image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8000
  onOpen: open-browser

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: echo 'init script' # runs during prebuild
  command: symfony server:start

# vscode:
#   extensions:
#     - sohibe.java-generate-setters-getters@4.2.2:TGDLfj6/6KwENqC9dWEGyQ==
